# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Distrbute app to firebase app  distribution"
  lane :distribute  do
    sh "flutter clean"
    sh "flutter build apk --release --flavor staging -t lib/main_stg.dart"
   firebase_app_distribution(
    app: "1:201286627640:android:27c5bcaf43e62b080e11cd",
    firebase_cli_token:ENV["FIREBASE_CLI_TOKEN"],
  android_artifact_type:"APK",
  release_notes:"new realse to test",
  testers:"alanasrabwalswd@gmail.com",
  android_artifact_path:"../build/app/outputs/flutter-apk/app-staging-release.apk"
  
  )

  end
end
